---
# https://github.com/kubewarden/trusted-repos-policy
#
apiVersion: policies.kubewarden.io/v1alpha2
kind: AdmissionPolicy
metadata:
  name: trusted-repos-policy
spec:
  module: "ghcr.io/kubewarden/policies/trusted-repos:v0.1.7"
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
    operations:
    - CREATE
    - UPDATE
  mutating: false
  settings:
    tags:
      reject:
        - latest
