repositories:
  - name: linkerd
    url: https://helm.linkerd.io/stable

helmDefaults:
  createNamespace: true
  timeout: 180 
  atomic: true
  verify: false
  wait: true

releases:
  - name: linkerd
    namespace: linkerd
    chart: linkerd/linkerd2
    disableValidationOnInstall: true
    wait: true
    waitForJobs: true
    values:
      - installCRDS: true

