---
# k3d cluster create lab --volume /dev/mapper/:/dev/mapper/
# k3d cluster delete lab
# helmfile --file rancher.yaml sync

repositories:
  - name: rancher
    url: https://releases.rancher.com/server-charts/latest
helmDefaults:
  createNamespace: true
  timeout: 180
  atomic: true
  verify: false
  wait: true

releases:
  - name: rancher
    namespace: cattle-system
    chart: rancher/rancher
    disableValidationOnInstall: true
    wait: true
    waitForJobs: true
    values:
      - hostname: rancher.local.olbalk.com
      - bootstrapPassword: admin

