---
# k3d cluster create lab --volume /dev/mapper/:/dev/mapper/
# k3d cluster delete lab
# helmfile --file rancher.yaml sync

repositories:
  - name: cert-manager
    url: https://charts.jetstack.io
  - name: traefik
    url: https://helm.traefik.io/traefik
  - name: rancher
    url: https://releases.rancher.com/server-charts/latest
helmDefaults:
  createNamespace: true
  timeout: 180
  atomic: true
  verify: false
  wait: true

releases:
  - name: cert-manager
    namespace: cert-manager
    chart: cert-manager/cert-manager
    disableValidationOnInstall: true
    wait: true
    waitForJobs: true
    values:
      - installCRDs: true
    # version: 1.6.1
  - name: traefik
    namespace: traefik
    chart: traefik/traefik
    wait: true
    waitForJobs: true
    disableValidationOnInstall: true
    # version: 10.3.4
  - name: rancher
    namespace: cattle-system
    chart: rancher/rancher
    disableValidationOnInstall: true
    wait: true
    waitForJobs: true
    values:
      - hostname: rancher.local.olbalk.com
      - bootstrapPassword: admin

  #    # current password H4LBmzEzWih4tiN1


