repositories:
  - name: traefik
    url: https://helm.traefik.io/traefik

helmDefaults:
  createNamespace: true
  timeout: 180 
  atomic: true
  verify: false
  wait: true

releases:
  - name: traefik
    namespace: traefik
    chart: traefik/traefik
    wait: true
    waitForJobs: true
    disableValidationOnInstall: true
    # version: 10.3.4

